# Game Systems and their associated factions
# This file is used by the seed:game_systems rake task

game_systems:
  - name: "Epic Armageddon - FERC"
    description: 
      en: "6mm strategy – French community-maintained lists"
      fr: "Stratégie en 6mm – listes maintenues par la communauté française"
    scoring_systems:
      - name: 'Grand Tournoi'
        description: "<table><thead><tr><th>Victoire par :</th><th>  - au T3 -  </th><th>  - au T4 -  </th></tr></thead><tbody><tr><td>3 objectifs ou plus</td><td>32 - 0</td><td>30 - 2</td></tr><tr><td>2 objectifs de différence</td><td>30 - 2</td><td>28 - 4</td></tr><tr><td>1 objectif de différence, et au moins 2 objectifs   </td><td>28 - 8</td><td>26 - 6</td></tr><tr><td>Egalité, ou aucun joueur n'a deux objectifs</td><td colspan=2></td></tr><tr><td>Plus de 250 pts d'écart au kill point</td><td></td><td>18- 14</td></tr><tr><td>Moins de 250 pts d'écart au kill point</td><td></td><td>16 - 16</td></tr></tbody></table>"
        fix_total_score: 32
        min_difference_for_win: 5
        is_default: true
    factions:
      - "Adeptus Astartes"
      - "White Scars"
      - "Raven Guard"
      - "Space Wolves"
      - "Black Templars"
      - "Imperial Fists"
      - "Blood Angels"
      - fr: "Légion d'Acier"
        en: "Steel Legion"
      - fr: "Death Korp de Krieg"
        en: "Death Korp of Krieg"
      - "Paras Elysiens"
      - "Premiers-Nés Vostroyens"
      - "Légions Titaniques"
      - "Adeptus Mechanicus"
      - "Chevaliers Impériaux"
      - "Adepta Sororitas"
      - "Adeptus Arbites"
      - "Black Legion"
      - "Iron Warriors"
      - "Egarés et Damnés"
      - "World Eaters"
      - "Thousand Sons"
      - "Death Guard"
      - "Emperor's Children"
      - "Eldars de Biel-Tan"
      - "Eldars de Ulthwé"
      - "Eldar de Yme-Loc"
      - "Eldar de Iyanden"
      - fr: "Eldars Noirs"
        en: "Dark Eldars"
      - "Tyranides"
      - "Squats"
      - "Empire T'au"
      - "Orks de Ghazghkull"
      - "Orks Evil Sunz"
      - "Orkimedes"
      - "Nécrons"
      - en: "Grey Knights"
        fr: "Chevaliers Gris"
      - "Adeptus Custodes"
      - "Hérésie d'Horus 30k"
      - en: "Chaos Daemons"
        fr: "Démons du Chaos"

  - name: "Warhammer 40k"
    description: "The best known Games Workshop game"
    factions:
      - "Chaos Knights"
      - "Agents de l'Imperium"
      - "Empire T'au"
      - "Space Wolves"
      - "Orks"
      - "Thousand Sons"
      - "Dark Angels"
      - "World Eaters"
      - "Tyranids"
      - "Aeldari"
      - "Space Marines du Chaos"
      - "Astra Militarum"
      - "Nécrons"
      - "Emperor's Children"
      - "Death Guard"
      - "Adeptus Custodes"
      - "Adepta Sororitas"
      - "Space Marines"
      - "Cultes Genestealers"
      - "Adeptus Mechanicus"
      - "Blood Angels"
      - "Deathwatch"
      - "Imperial Knights"
      - "Chevaliers Gris"
      - "Démons du Chaos"
      - "Drukhari"
      - "Leagues of Votann"
      - "Black Templars"

  - name: "Epic UK"
    description:
      en: "6mm strategy – UK Epic Armageddon lists for tournaments (Epic UK)"
      fr: "Stratégie en 6mm – listes Epic Armageddon maintenues au Royaume-Uni (Epic UK)"
    factions:
      - "Codex Space Marines"
      - "White Scars"
      - "Black Templars"
      - "Blood Angels"
      - "Dark Angels"
      - "Space Wolves"
      - "Imperial Fists"
      - "Steel Legion"
      - "Ulani Tank Regiment"
      - "Vanaheim Air Cavalry"
      - "Siege Masters"
      - "Death Korps"
      - "Biel-Tann"
      - "Iyanden"
      - "Saim-Hann"
      - "Ulthwé"
      - "Alaitoc"
      - "Yme-Loc"
      - "Tau"
      - "Vior’la Tau"
      - "Ghazgkhull Ork Horde"
      - "Feral Orks"
      - "Speed Freaks"
      - "Lost & the Damned"
      - "Black Legion"
      - "Death Guard"
      - "Emperors Children"
      - "Thousand Sons"
      - "World Eaters"
      - "Iron Warriors"
      - "Red Corsairs"
      - "Tyranids"
      - "Necrons"
      - "Dark Eldar"
      - "AMTL"
      - "Skitarii"
      - "Knights"
      - "Squats"
      - "Adepta Sororitas"
      - "Adeptus Titanicus"
      - "Albork Orkstein’s Ork Gargant Mob"
      - "Dai-Tan Titan Craftworld"
      - "Tyranid Bio-Titans"

  - name:
      en: "OPR Grimdark Future"
      fr: "OPR Grimdark Future"
    description:
      en: "Sci‑fi mass battle by One Page Rules — official army books"
      fr: "Bataille de masse sci‑fi par One Page Rules — livres d'armées officiels"
    factions:
      - "Alien Hives"
      - "Battle Brothers"
      - "Blood Brothers"
      - "Dark Brothers"
      - "Knight Brothers"
      - "Watch Brothers"
      - "Wolf Brothers"
      - "Blessed Sisters"
      - "Custodian Brothers"
      - "DAO Union"
      - "Dark Elf Raiders"
      - "Dwarf Guilds"
      - "Elven Jesters"
      - "Eternal Dynasty"
      - "Goblin Reclaimers"
      - "Havoc Brothers"
      - "Change Disciples"
      - "Lust Disciples"
      - "Plague Disciples"
      - "War Disciples"
      - "High Elf Fleets"
      - "Human Defense Force"
      - "Human Inquisition"
      - "Infected Colonies"
      - "Jackals"
      - "Machine Cult"
      - "Orc Marauders"
      - "Prime Brothers"
      - "Blood Prime Brothers"
      - "Dark Prime Brothers"
      - "Knight Prime Brothers"
      - "Watch Prime Brothers"
      - "Wolf Prime Brothers"
      - "Ratmen Clans"
      - "Rebel Guerrillas"
      - "Robot Legions"
      - "Saurian Starhost"
      - "Soul‑Snatcher Cult"
      - "Titan Lords"
      - "Wormhole Daemons"
      - "Daemons of Change"
      - "Daemons of Lust"
      - "Daemons of Plague"
      - "Daemons of War"
